<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FTR3COF93BK8A76" ignored="8" name="Default test" tests="1" failures="1" timestamp="2022-07-05T01:30:44 EDT" time="156.882" errors="0">
  <testcase name="EMS_084_CATS_ProcessD_NoProcess_Approved_UncheckBackdown_SW" time="128.038" classname="TestCases.GUIs">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	@@line_start [509] line_end; expected [07-09-22  0818P] but found [07-09-22 0818P]gui_start  gui_end">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
@@line_start [509] line_end; expected [07-09-22  0818P] but found [07-09-22 0818P]gui_start  gui_end
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestCases.GUIs.EMS_084_CATS_ProcessD_NoProcess_Approved_UncheckBackdown_SW(GUIs.java:647)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- EMS_084_CATS_ProcessD_NoProcess_Approved_UncheckBackdown_SW -->
  <testcase name="GUI_29_Queue_viewl_and_journal_TZ_display_not_match" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_29_Queue_viewl_and_journal_TZ_display_not_match -->
  <testcase name="GUI_10_Bill_Record_W" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_10_Bill_Record_W -->
  <testcase name="GUI_03_RUD_SW" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_03_RUD_SW -->
  <testcase name="GUI_16_Service_Summary_Area" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_16_Service_Summary_Area -->
  <testcase name="GUI_34_bim_info_in_Bill_MW" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_34_bim_info_in_Bill_MW -->
  <testcase name="GUI_04_RUD_W" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_04_RUD_W -->
  <testcase name="GUI_36_BILL_inforamtion_not_back_again" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_36_BILL_inforamtion_not_back_again -->
  <testcase name="GUI_45_City_and_State_in_Middle_Section_MW" time="0.0" classname="TestCases.GUIs">
    <ignored/>
  </testcase> <!-- GUI_45_City_and_State_in_Middle_Section_MW -->
</testsuite> <!-- Default test -->
